const products = [
  {id:1,cat:'sillas',name:'Silla de ruedas manual Comfort',price:589900,desc:'Plegable, liviana y con reposapiés ajustables.',icon:'♿',badge:'Más vendida'},
  {id:2,cat:'sillas',name:'Silla de ruedas eléctrica Move Pro',price:3299900,desc:'Motor eléctrico, control intuitivo y autonomía para trayectos diarios.',icon:'♿',badge:'Premium'},
  {id:3,cat:'sillas',name:'Silla de traslado compacta',price:429900,desc:'Diseño práctico para traslados cortos y espacios reducidos.',icon:'♿',badge:'Práctica'},
  {id:4,cat:'muletas',name:'Muletas axilares ajustables',price:149900,desc:'Altura regulable y apoyos acolchados para mayor comodidad.',icon:'🦯',badge:'Popular'},
  {id:5,cat:'muletas',name:'Muleta canadiense ergonómica',price:179900,desc:'Apoyo antebraquial y agarre cómodo para uso prolongado.',icon:'🦯',badge:'Confort'},
  {id:6,cat:'andadores',name:'Andador plegable con ruedas',price:269900,desc:'Estructura liviana, plegado fácil y apoyo estable.',icon:'🚶',badge:'Funcional'},
  {id:7,cat:'andadores',name:'Andador de aluminio estándar',price:199900,desc:'Cuatro puntos de apoyo y altura ajustable.',icon:'🚶',badge:'Clásico'},
  {id:8,cat:'accesorios',name:'Cojín antiescaras',price:189900,desc:'Cojín de soporte diseñado para mejorar la distribución de presión.',icon:'🛏️',badge:'Bienestar'},
  {id:9,cat:'accesorios',name:'Bastón ajustable de aluminio',price:69900,desc:'Altura ajustable y base estable para desplazamientos cotidianos.',icon:'🦯',badge:'Económico'},
  {id:10,cat:'accesorios',name:'Kit de accesorios para silla',price:129900,desc:'Bolso, soporte y elementos complementarios para uso diario.',icon:'🧰',badge:'Kit'},
  {id:11,cat:'sillas',name:'Silla deportiva ultraliviana',price:1499900,desc:'Marco liviano para usuarios activos que buscan maniobrabilidad.',icon:'♿',badge:'Especial'},
  {id:12,cat:'accesorios',name:'Mesa auxiliar para silla de ruedas',price:159900,desc:'Superficie práctica para actividades, alimentación y cuidado.',icon:'🧰',badge:'Útil'}
];

const state = {cart: JSON.parse(localStorage.getItem('miempresa_cart') || '[]'), user: JSON.parse(localStorage.getItem('miempresa_user') || 'null'), mode:'login'};
const money = n => new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n);
const save = () => localStorage.setItem('miempresa_cart',JSON.stringify(state.cart));

function renderProducts(){
  const grid=document.getElementById('productsGrid'); const q=document.getElementById('searchInput').value.toLowerCase().trim(); const cat=document.getElementById('categoryFilter').value;
  const list=products.filter(p=>(cat==='todos'||p.cat===cat)&&(!q||`${p.name} ${p.desc}`.toLowerCase().includes(q)));
  grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><span class="product-badge">${p.badge}</span><div class="product-icon" aria-hidden="true">${p.icon}</div></div><div class="product-body"><span class="product-category">${p.cat}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="price">${money(p.price)}</div><button class="btn btn-primary" data-add="${p.id}">Agregar al carrito</button></div></article>`).join('') || '<div class="empty-state">No encontramos productos con esos criterios.</div>';
  grid.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(Number(b.dataset.add))));
}
function addToCart(id){ const item=state.cart.find(x=>x.id===id); if(item)item.qty++; else state.cart.push({id,qty:1}); save(); renderCart(); openDrawer('cartDrawer'); }
function changeQty(id,d){const item=state.cart.find(x=>x.id===id);if(!item)return;item.qty+=d;if(item.qty<=0)state.cart=state.cart.filter(x=>x.id!==id);save();renderCart();}
function totals(){const subtotal=state.cart.reduce((s,x)=>{const p=products.find(p=>p.id===x.id);return s+(p?p.price*x.qty:0)},0);return {subtotal,tax:Math.round(subtotal*.19),total:Math.round(subtotal*1.19)}}
function renderCart(){
  const el=document.getElementById('cartItems'); document.getElementById('cartCount').textContent=state.cart.reduce((s,x)=>s+x.qty,0);
  if(!state.cart.length)el.innerHTML='<div class="empty-state">Tu carrito está vacío.<br>Agrega productos para continuar.</div>'; else el.innerHTML=state.cart.map(x=>{const p=products.find(p=>p.id===x.id);return `<div class="cart-item"><div class="cart-thumb">${p.icon}</div><div><h4>${p.name}</h4><small>${money(p.price)}</small><div class="qty"><button data-q="${p.id}" data-d="-1">−</button><strong>${x.qty}</strong><button data-q="${p.id}" data-d="1">+</button></div></div><strong>${money(p.price*x.qty)}</strong></div>`}).join('');
  el.querySelectorAll('[data-q]').forEach(b=>b.addEventListener('click',()=>changeQty(Number(b.dataset.q),Number(b.dataset.d))));
  const t=totals(); document.getElementById('subtotal').textContent=money(t.subtotal);document.getElementById('tax').textContent=money(t.tax);document.getElementById('total').textContent=money(t.total); document.getElementById('checkoutBtn').disabled=!state.cart.length;
}
function openDrawer(id){document.getElementById(id).classList.add('open');document.getElementById(id).setAttribute('aria-hidden','false')}
function closeModal(id){document.getElementById(id).classList.remove('open');document.getElementById(id).setAttribute('aria-hidden','true')}
function openAccount(){renderAccount();openDrawer('accountModal')}
function renderAccount(){const v=document.getElementById('accountView');if(state.user){v.innerHTML=`<span class="eyebrow">MI CUENTA</span><h3>Hola, ${state.user.name}</h3><div class="account-user"><span>👤</span><div><strong>${state.user.email}</strong><small>Cuenta guardada localmente en este dispositivo.</small></div></div><button class="btn btn-secondary full" id="logoutBtn" style="margin-top:14px">Cerrar sesión</button>`;document.getElementById('logoutBtn').onclick=()=>{state.user=null;localStorage.removeItem('miempresa_user');renderAccount();}}else{v.innerHTML=`<div class="account-form"><span class="eyebrow">MI CUENTA</span><h3>${state.mode==='login'?'Iniciar sesión':'Crear cuenta'}</h3><form id="accountForm"><label>Nombre${state.mode==='login'?'':'<input required name="name" placeholder="Tu nombre" />'}</label><label>Email<input required type="email" name="email" placeholder="nombre@correo.com" /></label><label>Contraseña<input required type="password" minlength="6" name="password" placeholder="Mínimo 6 caracteres" /></label><button class="btn btn-primary full">${state.mode==='login'?'Entrar':'Crear cuenta'}</button></form><div class="account-switch">${state.mode==='login'?'¿Aún no tienes cuenta?':'¿Ya tienes una cuenta?'} <button id="switchAccount">${state.mode==='login'?'Crear cuenta':'Iniciar sesión'}</button></div></div>`;document.getElementById('accountForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.user={name:f.get('name')||String(f.get('email')).split('@')[0],email:f.get('email')};localStorage.setItem('miempresa_user',JSON.stringify(state.user));renderAccount()};document.getElementById('switchAccount').onclick=()=>{state.mode=state.mode==='login'?'register':'login';renderAccount()};}}
function openPayment(){if(!state.cart.length)return;openDrawer('cartDrawer');closeModal('cartDrawer');openDrawer('paymentModal');renderPaymentStart()}
function renderPaymentStart(){document.getElementById('paymentFormArea').innerHTML='<div class="success">Selecciona un método. El checkout está preparado para conectar el proveedor real de pagos.</div>';document.querySelectorAll('.payment-option').forEach(b=>b.onclick=()=>renderPaymentForm(b.dataset.method));}
function renderPaymentForm(method){const labels={card:'Tarjeta de crédito / débito',pse:'Pago con PSE',paypal:'PayPal'};const area=document.getElementById('paymentFormArea');if(method==='card')area.innerHTML=`<div class="payment-fields"><label>Número de tarjeta<input placeholder="0000 0000 0000 0000" /></label><div class="form-row"><label>Vencimiento<input placeholder="MM/AA" /></label><label>CVV<input placeholder="123" /></label></div><button class="btn btn-primary full" id="simulatePayment">Pagar ${money(totals().total)}</button></div>`; else if(method==='pse') area.innerHTML=`<div class="payment-fields"><label>Banco<select><option>Selecciona tu banco</option><option>Bancolombia</option><option>Davivienda</option><option>BBVA</option><option>Banco de Bogotá</option></select></label><button class="btn btn-primary full" id="simulatePayment">Continuar a PSE</button></div>`; else area.innerHTML=`<div class="payment-fields"><p style="font-size:12px;color:var(--muted)">Serás redirigido a PayPal para autorizar el pago.</p><button class="btn btn-primary full" id="simulatePayment">Continuar con PayPal</button></div>`;document.getElementById('simulatePayment').onclick=()=>{const orderId='ME-'+Date.now().toString().slice(-8);state.cart=[];save();renderCart();area.innerHTML=`<div class="success">Pedido ${orderId} creado correctamente en modo demostración. Para cobrar de verdad, conecta tu cuenta de pagos y activa los webhooks del proveedor.</div>`;};}

document.getElementById('cartBtn').onclick=()=>openDrawer('cartDrawer');document.getElementById('accountBtn').onclick=openAccount;document.getElementById('accountBtnFooter').onclick=openAccount;document.getElementById('checkoutBtn').onclick=openPayment;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
document.querySelectorAll('.category-card').forEach(b=>b.onclick=()=>{document.getElementById('categoryFilter').value=b.dataset.filter;renderProducts();document.getElementById('productos').scrollIntoView({behavior:'smooth'});});
document.getElementById('categoryFilter').onchange=renderProducts;document.getElementById('searchInput').oninput=renderProducts;
document.getElementById('quoteForm').onsubmit=async e=>{e.preventDefault();const status=document.getElementById('quoteStatus');status.className='form-status';status.textContent='Enviando solicitud…';try{const res=await fetch('/api/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});if(!res.ok)throw new Error('No se pudo enviar');status.className='form-status success';status.textContent='¡Solicitud enviada! Nuestro equipo comercial la recibió.';e.target.reset();}catch(err){status.className='form-status danger';status.textContent='No se pudo enviar automáticamente. Revisa la configuración del servidor SMTP en .env.';}};
[document.getElementById('cartDrawer'),document.getElementById('accountModal'),document.getElementById('paymentModal')].forEach(el=>el.addEventListener('click',e=>{if(e.target===el)closeModal(el.id)}));
renderProducts();renderCart();
